var a7b = require('./a7b');
var is = require('./is');

console.log("#1 START");
console.log(is.take(a7b.makeSqrtSeq(2,1),5));
console.log("#1 END");
console.log("");
console.log("#2 START");
console.log(is.take(a7b.makeSqrtSeq(10000,1),10));
console.log("#2 END");
console.log("");
console.log("#3 START");
console.log(a7b.sqrt(a7b.makeSqrtSeq(2,1),1));
console.log("#3 END");
console.log("");
console.log("#4 START");
console.log(a7b.sqrt(a7b.makeSqrtSeq(2,1),0.1));
console.log("#4 END");
console.log("");
console.log("#5 START");
console.log(a7b.sqrt(a7b.makeSqrtSeq(2,1),1e-2));
console.log("#5 END");
console.log("");
console.log("#6 START");
console.log(is.take(a7b.cumulate(is.from(1)),10));
console.log("#6 END");
console.log("");
console.log("#7 START");
console.log(is.take(a7b.cumulate(is.iterates(function(n){return n * 2;}, 1)), 10));
console.log("#7 END");
